# Generated by Django 5.0.6 on 2024-05-20 01:02

import asistencia.models
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula_id', models.CharField(max_length=10, unique=True)),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=25)),
                ('Correo', models.CharField(max_length=40)),
                ('Telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=6, unique=True)),
                ('Nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Materia',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula_id', models.CharField(max_length=10, unique=True)),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=25)),
                ('Correo', models.CharField(max_length=40)),
                ('Telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto_qr', models.TextField(unique=True)),
                ('direccion', models.ImageField(upload_to=asistencia.models.ruta_qr)),
                ('usado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'QR',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Materia_X_Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=6, unique=True)),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.materia')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.profesores')),
            ],
            options={
                'db_table': 'materiasXprofesor',
            },
        ),
        migrations.CreateModel(
            name='Alumnos_X_Materia_X_Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.alumnos')),
                ('id_mat_prof', models.ForeignKey(db_column='id_mat_prof', on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.materia_x_profesor')),
            ],
            options={
                'db_table': 'alumnosXmateria',
            },
        ),
        migrations.CreateModel(
            name='Asistencia_X_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alum_mat_prof', models.ForeignKey(db_column='id_alum_mat_prof', on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.alumnos_x_materia_x_profesor')),
                ('id_qr', models.ForeignKey(db_column='id_qr', on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.qr')),
            ],
        ),
    ]
