# Generated by Django 5.0.6 on 2024-05-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asistencia_x_alumno',
            table='asistenciaXalumno',
        ),
    ]
