# Generated by Django 5.0.6 on 2024-05-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alumnos_id_usuario_profesores_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='id_alumno',
            field=models.ForeignKey(db_column='id_alumno', default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.alumnos'),
            preserve_default=False,
        ),
    ]
