# Generated by Django 5.0.6 on 2024-05-20 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_qr_id_alumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='id_alumno',
        ),
        migrations.AddField(
            model_name='qr',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
