# Generated by Django 5.0.6 on 2024-05-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_remove_qr_id_alumno_qr_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='id_alum_mat_prof',
            field=models.ForeignKey(db_column='id_alum_mat_prof', default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.alumnos_x_materia_x_profesor'),
            preserve_default=False,
        ),
    ]
